# Generated by Django 3.0 on 2024-01-08 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': 'Дом', 'verbose_name_plural': 'Дома'},
        ),
    ]
