# Generated by Django 3.0 on 2024-01-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_auto_20240108_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ('name', 'price'), 'verbose_name': 'Дом', 'verbose_name_plural': 'Дома'},
        ),
        migrations.AddField(
            model_name='house',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='houses/photos', verbose_name='Фото'),
        ),
    ]
